#!/usr/bin/env python3
from __future__ import annotations

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = {
    "wwc_original": ROOT / "WWC-export-archive-2025-Aug-25-172838" / "Interventions_Studies_And_Findings.csv",
    "wwc_aggregated": ROOT / "Urvi_Analysis" / "asadata_aggregated.csv",
}
OUT_SQL = ROOT / "db" / "init" / "01_schema.sql"
OUT_MAP_DIR = ROOT / "db" / "column_mappings"


def sanitize(name: str) -> str:
    c = name.strip().lower()
    c = re.sub(r"[^a-z0-9]+", "_", c)
    c = re.sub(r"_+", "_", c).strip("_")
    if not c:
        c = "col"
    if c[0].isdigit():
        c = f"c_{c}"
    return c


def read_header(path: Path) -> list[str]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        return next(reader)


def build_mapping(headers: list[str]) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    used: dict[str, int] = {}
    for h in headers:
        base = sanitize(h)
        n = used.get(base, 0) + 1
        used[base] = n
        col = base if n == 1 else f"{base}__{n}"
        out.append((h, col))
    return out


def quote_ident(s: str) -> str:
    return '"' + s.replace('"', '""') + '"'


def emit_create_table(table: str, mapping: list[tuple[str, str]], source_path: Path) -> str:
    cols = ",\n".join(f"    {quote_ident(new)} TEXT" for _, new in mapping)
    return (
        f"-- source: {source_path.as_posix()}\n"
        f"DROP TABLE IF EXISTS raw.{table};\n"
        f"CREATE TABLE raw.{table} (\n{cols}\n);\n"
    )


def main() -> None:
    OUT_MAP_DIR.mkdir(parents=True, exist_ok=True)
    parts = [
        "-- Auto-generated by db/scripts/generate_schema.py",
        "CREATE SCHEMA IF NOT EXISTS raw;",
        "",
    ]

    for table, path in SRC.items():
        headers = read_header(path)
        mapping = build_mapping(headers)

        map_path = OUT_MAP_DIR / f"{table}_columns.csv"
        with map_path.open("w", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["source_column", "db_column"])
            writer.writerows(mapping)

        parts.append(emit_create_table(table, mapping, path))

    OUT_SQL.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT_SQL}")
    for p in sorted(OUT_MAP_DIR.glob("*_columns.csv")):
        print(f"Wrote {p}")


if __name__ == "__main__":
    main()
